# render.yaml
services:
  - type: web
    name: romapp-backend
    env: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: atlas-credentials
          key: MONGODB_URI

  - type: static
    name: romapp-frontend
    env: static
    branch: main
    plan: free
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://romapp-backend.onrender.com
