
# render.yaml
services:
  - type: web
    name: romapp-backend
    env: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: atlas-credentials
          key: MONGODB_URI
