name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy via Render CLI
        uses: render-examples/deploy-render@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: romapp-backend
          force: true
